project_id = "tcupxcxyylxfgsbhfdhw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54324

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54329

[functions]
verify_jwt = true  # padrão fechado

# ---- PÚBLICAS (sem JWT) ----
[functions."google-drive-oauth-callback"]
verify_jwt = false
[functions."thumb-open"]
verify_jwt = false
[functions."drive-thumb-open"]
verify_jwt = false
[functions."drive-thumb-signed"]
verify_jwt = false
[functions."hello-open"]
verify_jwt = false
[functions."diag-list-root"]
verify_jwt = false
[functions."diag-list-folder"]
verify_jwt = false
[functions."diag-env"]
verify_jwt = false

# ---- PRIVADAS (com JWT) ----
[functions."google-drive-auth"]
verify_jwt = true
[functions."drive-changes-peek"]
verify_jwt = true
[functions."drive-changes-pull"]
verify_jwt = true
[functions."drive-index-folder"]
verify_jwt = true
[functions."drive-sync-now"]
verify_jwt = true
[functions."drive-thumb"]
verify_jwt = true
[functions."get-thumb-urls"]
verify_jwt = true
[functions."diag-scopes"]
verify_jwt = true
[functions."diag-user-tokens"]
verify_jwt = true
[functions."library-list-gdrive"]
verify_jwt = true