project_id = "tcupxcxyylxfgsbhfdhw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54324

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54329

# ----- DEFAULT: SECURE (com JWT) — PRODUÇÃO -----
[functions]
verify_jwt = true  # ✅ Secure by default

# ===== PRIVADAS (com JWT = true) =====
[functions."google-drive-auth"]
verify_jwt = true

[functions."drive-changes-peek"]
verify_jwt = true

[functions."drive-changes-pull"]
verify_jwt = true

[functions."drive-index-folder"]
verify_jwt = true

[functions."drive-sync-now"]
verify_jwt = true

[functions."drive-sync-start"]
verify_jwt = true

[functions."drive-sync-run"]
verify_jwt = true

[functions."drive-sync-diagnostics"]
verify_jwt = true

[functions."drive-folder-verify"]
verify_jwt = true

[functions."drive-thumb"]           # proxy com JWT do usuário
verify_jwt = true

[functions."get-thumb-urls"]        # emite URLs assinadas
verify_jwt = true

[functions."drive-thumb-fetch"]      # gera e cacheia thumbnails com storage
verify_jwt = true

# Removed get-video-urls - now using get-thumb-urls for all media

[functions."diag-scopes"]
verify_jwt = true

[functions."diag-user-tokens"]      # sensível
verify_jwt = true

[functions."library-list-gdrive"]
verify_jwt = true

[functions."library-list-unified"]
verify_jwt = true

[functions."labels-assign"]
verify_jwt = true

[functions."delete-unified-item"]
verify_jwt = true

# ===== PÚBLICAS (explicitamente liberadas) =====
# Callback do OAuth (Google não envia JWT)
[functions."google-drive-oauth-callback2"]
verify_jwt = false

# Thumbs abertas assinadas (validação via HMAC interno)
[functions."thumb-open"]
verify_jwt = false

# Removed video-open - now using thumb-open for all media

# ===== PREVIEW FUNCTIONS (com JWT = true) =====
[functions."drive-image-preview"]
verify_jwt = true

[functions."drive-video-poster"] 
verify_jwt = true
